'''print("hii")

a = "aman"
b = 20.25
c = 23
print("My name is :",a,"my age is:",c)'''

'''a = 23
b = 24
sum=a+b
print(sum)'''

#use input function]

'''name = input("what's your name :")
print(name)
age = 23
print("what's your name :",name,"what is your age:",age)'''
#(start value,end value)
#(start value,end value,step value)
'''for i in range(1,11):
    print(i)
else:
    ("hii")

for i in range(2,21,2):
    print(i)

for i in range(10,0,-1):
    print(i)'''

#for i in range (1,100):
 #   if i
'''for i in range(0,101,2):
    print(i)'''



